### ISSUE TITLE
Error @ UI.php#L123

### ISSUE THREAD

**Issue by Endermanbugzjfc** [GabBiswajit/SkyblockGB#1]
https://crash.pmmp.io/view/9153904
https://github.com/GabBiswajit/SkyblockGB/blob/3f1503ad9fb743d4b0cbf309c5f4507edf8583b2/src/Biswajit/Skyblock/menu/UI.php#L97-L123

**Comment by Endermanbugzjfc** [comment]
Please use IDE (PHPStorm) or static analysis tool (PHPStan) to catch all errors before calling it a "working plugin".

**Comment by GabBiswajit** [comment]
Don't have pc using phone. Btw it's now fix
