### ISSUE TITLE
Error @ UI.php#58

### ISSUE THREAD

**Issue by Endermanbugzjfc** [GabBiswajit/SkyblockGB#3]
https://crash.pmmp.io/view/9153975
https://github.com/GabBiswajit/SkyblockGB/blob/f5c7f903c71ed4b4564806c774c17703dd0f660c/src/Biswajit/Skyblock/menu/UI.php#L48-L58

**Comment by GabBiswajit** [comment]
Really Uff Try Lot's Time To Invite But See This Glitch For Frist Time.

**Comment by justauser001** [comment]
Add Npc And Portal Feature/System

**Comment by GabBiswajit** [comment]
$result = isset($data[1]) ? (string) $data[1] : ""; @Endermanbugzjfc this maybe works or I will fix it Later I am out of my city.

**Comment by GabBiswajit** [comment]
@justauser001 please this is a bug report create your new issue this full explanation off your function.

**Comment by Endermanbugzjfc** [comment]
> $result = isset($data[1]) ? (string) $data[1] : ""; @Endermanbugzjfc this maybe works or I will fix it Later I am out of my city.

hmm why github didnt notify me this msg??

**Comment by GabBiswajit** [comment]
Idk

**Comment by Endermanbugzjfc** [comment]
@GabBiswajit
```php
$result = $data[0] ?? "";
```
(Array starts at 0)

**Comment by GabBiswajit** [comment]
Hmm thanks
