### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nhaco90678** [GabBiswajit/SkyblockGB#4]
As I entered the game, it goes directly to the island from the lobby + it should be delete the island

**Comment by GabBiswajit** [comment]
Delete the Island?? Join island join is a function

**Comment by nhaco90678** [comment]
what i mean is i say delete island should be added to island menu . The other issue is that it directs to the island as we enter the game, it is normal. from the lobby to the island by typing a command

**Comment by GabBiswajit** [comment]
`/join` and delete island is reset island is same

**Comment by nhaco90678** [comment]
![Uploading IMG_20230903_114647.jpg…]()
.

**Comment by GabBiswajit** [comment]
Image can't load here..

**Comment by nhaco90678** [comment]
my pp

**Comment by GabBiswajit** [comment]
Why need delete island you use reset island it's same
