### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Satyarth9914** [GabBiswajit/SkyblockGB#5]
PocketMine-MP Crash Dump Sun Sep 3 20:13:24 UTC 2023

PocketMine-MP version: 5.4.3 [Protocol 594]
Git commit: e852a4382116705d7558fd808f1b388666b0c0cb
PHP version: 8.1.22
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: SkyblockGB

Thread: Main
Error: Target directory path does not exist or is not a directory
File: pmsrc/src/utils/Filesystem
Line: 241
Type: RuntimeException
Backtrace:
#0 pmsrc/src/utils/Config(239): pocketmine\utils\Filesystem::safeFilePutContents(string[63] /home/container/plugin_data/SkyblockGB/players/Satyarthking.yml, string[11] --- [].....)
#1 pmsrc/src/utils/Config(162): pocketmine\utils\Config->save()
#2 pmsrc/src/utils/Config(117): pocketmine\utils\Config->load(string[63] /home/container/plugin_data/SkyblockGB/players/Satyarthking.yml, int 2, array[0])
#3 plugins/SkyblockGB_dev-14.phar/src/Biswajit/Skyblock/Skyblock(110): pocketmine\utils\Config->__construct(string[63] /home/container/plugin_data/SkyblockGB/players/Satyarthking.yml, int 2, array[0])
#4 plugins/SkyblockGB_dev-14.phar/src/Biswajit/Skyblock/API(116): Biswajit\Skyblock\Skyblock->getPlayerFile(string[12] Satyarthking)
#5 plugins/SkyblockGB_dev-14.phar/src/Biswajit/Skyblock/EventHandler(121): Biswajit\Skyblock\API->registerPlayer(object pocketmine\player\Player#93296)
#6 pmsrc/src/event/RegisteredListener(61): Biswajit\Skyblock\EventHandler->onJoin(object pocketmine\event\player\PlayerJoinEvent#106721)
#7 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#106721)
#8 pmsrc/src/player/Player(889): pocketmine\event\Event->call()
#9 pmsrc/src/network/mcpe/NetworkSession(825): pocketmine\player\Player->doFirstSpawn()
#10 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(37): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
#11 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#106805)
#12 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#127095)
#13 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#106805, string[2] q.)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(218): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[56] c*d.............~'..i....a{CC....c#...vXt?.. ^..X..55...)
#15 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[65] .....T.1.I......&n..........A.....P.3.0...(.s..Q.OJFej..7&...!Eh[)
#16 pmsrc/src/network/mcpe/raklib/RakLibInterface(110): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#120239)
#17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#18 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#20 pmsrc/src/Server(1690): pocketmine\snooze\SleeperHandler->sleepUntil(float 1693772004.0771)
#21 pmsrc/src/Server(1064): pocketmine\Server->tickProcessor()
#22 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#23 pmsrc/src/PocketMine(357): pocketmine\server()
#24 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by GabBiswajit** [comment]
Delete your plugin data
